### ISSUE TITLE
Document expected time format in README and/or header 

### ISSUE THREAD

**Issue by altyus** [hyperoslo/NSManagedObject-HYPPropertyMapper#66]
Would be useful for library users to have guidance on what types of date strings can be mapped without modifying the library.  It would be even more useful if users could pass in their own date formatter, in cases where API's aren't using iso8601.  For example: my date string from a Django Rest Framework backed api is "2015-05-27T13:51:41.971000-0400".  This is silently returning nil in `+ (NSDate *)hyp_dateFromISO8601String:(NSString *)iso8601`

**Comment by 3lvis** [comment]
Hi Al,

We went for just supporting ISO8601 out of the box because that's the most common format when parsing dates, also we have a [quite performant way to parse this strings](https://github.com/hyperoslo/NSManagedObject-HYPPropertyMapper/blob/master/Source/NSManagedObject%2BHYPPropertyMapper.m#L272-L319) which overcomes the performance issues of using `NSDateFormatter`.

We are trying to keep the parsing simple and moving this type of processing [to libraries that pre-process the JSON](https://github.com/hyperoslo/Minced) before sending them to HYPPropertyMapper.

Maybe we can figure out a library that can pre-process strings into ISO8601 dates! Do you think that would work?

**Comment by altyus** [comment]
Yes, I saw the nice little algorithm, I was just hoping to not have to fork it for our use case.  I guess the main point I was making with the issue was that it might be useful to spell that requirement out in the README.  I'm happy to submit a PR if it helps! Thanks for following up so quickly.

**Comment by 3lvis** [comment]
I improved the README with some information on Dates.

Thanks a lot for reporting this, you rock! \m/

https://github.com/hyperoslo/NSManagedObject-HYPPropertyMapper#dates

**Comment by altyus** [comment]
great thanks!
